
tests:
	@forge test --fork-url https://eth-mainnet.g.alchemy.com/v2/_k459_5wqx-_anLhMSPJPfddLM8qU_LM -vvvvv --match-test testFlashloan


test_static:
	@forge test --fork-url https://eth-mainnet.g.alchemy.com/v2/_k459_5wqx-_anLhMSPJPfddLM8qU_LM -vvvv --match-test testParams